/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shared;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.koneksi;
import model.UserSession;
import model.UIScaler; 


/**
 *
 * @author PUTRI SAHARA T
 */
public class FormAbsensiKaryawan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAbsensiKaryawan.class.getName());

    /**
     * Creates new form FormAbsensiKaryawan
     */
   public FormAbsensiKaryawan() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null); // Tengah layar
        UIScaler.scaleContainer(this.getContentPane());
        
        // --- 1. AUTO-FILL DATA DARI SESSION ---
        String idSaya = UserSession.getKaryawanId();
        String namaSaya = UserSession.getNamaKaryawan();
        String jabatanSaya = UserSession.getJabatanKaryawan();
        
        // Tempel ke Textfield
        textID.setText(idSaya);
        textnama.setText(namaSaya);
        
        // Set Jabatan di ComboBox (jcomboRole2)
        if(jabatanSaya != null) {
            jcomboRole2.setSelectedItem(jabatanSaya);
        }
        
        // Kunci Field agar tidak bisa diubah manual
        textID.setEditable(false);
        textnama.setEditable(false);
        jcomboRole2.setEnabled(false); // Matikan combo box jabatan
        
        // --- 2. SET WAKTU DEFAULT ---
        jdate.setDate(new java.util.Date()); // Tanggal hari ini
        
        // Format Spinner Jam agar tampil HH:mm:ss
        javax.swing.JSpinner.DateEditor deMasuk = new javax.swing.JSpinner.DateEditor(jammasuk, "HH:mm:ss");
        jammasuk.setEditor(deMasuk);
        jammasuk.setValue(new java.util.Date()); // Jam sekarang
        
        javax.swing.JSpinner.DateEditor dePulang = new javax.swing.JSpinner.DateEditor(jampulang, "HH:mm:ss");
        jampulang.setEditor(dePulang);
        jampulang.setValue(new java.util.Date()); // Jam sekarang
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnamakywn = new javax.swing.JButton();
        btnID = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jcomboRole1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        textnama = new javax.swing.JTextField();
        textID = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jdate = new com.toedter.calendar.JDateChooser();
        jampulang = new javax.swing.JSpinner();
        jammasuk = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jcomboRole2 = new javax.swing.JComboBox<>();
        jcombojbtn = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jTextField1.setText("Data Karyawan");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnamakywn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnamakywnActionPerformed(evt);
            }
        });

        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Nama Karyawan");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("ID Karyawan");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Jabatan");

        jcomboRole1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "HRD", "Karyawan", " " }));
        jcomboRole1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboRole1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("PENGGAJIAN");
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 23)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("STAFFLINK");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ABSENSI KARYAWAN");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PENGGAJIAN");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LOGOUT");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LAPORAN");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DATA KARYAWAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 156, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Nama Karyawan");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("ID Karyawan");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Tanggal");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Jam Masuk");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Jam Pulang");

        textnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnamaActionPerformed(evt);
            }
        });

        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        jampulang.setModel(new javax.swing.SpinnerDateModel());
        jampulang.setEditor(new javax.swing.JSpinner.DateEditor(jampulang, "HH-mm"));

        jammasuk.setModel(new javax.swing.SpinnerDateModel());
        jammasuk.setEditor(new javax.swing.JSpinner.DateEditor(jammasuk, "HH-mm"));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Jabatan");

        jcomboRole2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "HRD", "Karyawan", " " }));
        jcomboRole2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboRole2ActionPerformed(evt);
            }
        });

        jcombojbtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Izin", "Sakit" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Status");

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("ABSENSI KARYAWAN");
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        // Create main scroll pane for responsive layout
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        javax.swing.JPanel formContentPanel = new javax.swing.JPanel();
        formContentPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(10, 20, 10, 20);
        gbc.weightx = 1.0;

        int row = 0;

        // Nama Karyawan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel19, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textnama, gbc);
        row++;

        // ID Karyawan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel20, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textID, gbc);
        row++;

        // Role
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel25, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jcomboRole2, gbc);
        row++;

        // Tanggal
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel21, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jdate, gbc);
        row++;

        // Jam Masuk
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel22, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jammasuk, gbc);
        row++;

        // Jam Pulang
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel23, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jampulang, gbc);
        row++;

        // Status
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel2, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jcombojbtn, gbc);
        row++;

        // Separator
        javax.swing.JSeparator separator = new javax.swing.JSeparator();
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        formContentPanel.add(separator, gbc);
        row++;

        // Buttons
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
        buttonPanel.add(btnsimpan);
        buttonPanel.add(btnbatal);

        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);
        formContentPanel.add(buttonPanel, gbc);

        scrollPane.setViewportView(formContentPanel);

        // Main layout with sidebar and scroll pane
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnamakywnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnamakywnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnamakywnActionPerformed

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIDActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
       String idKaryawan = textID.getText();
        String status = jcombojbtn.getSelectedItem().toString(); // Mengambil Status (Hadir/Izin/Sakit)
        
        // Validasi
        if (idKaryawan.isEmpty() || jdate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Connection conn = koneksi.getKoneksi();
            
            // Format Tanggal & Jam untuk Database MySQL
            SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
            String tglAbsen = sdfDate.format(jdate.getDate());
            
            SimpleDateFormat sdfTime = new SimpleDateFormat("HH:mm:ss");
            String jamM = sdfTime.format(jammasuk.getValue());
            String jamP = sdfTime.format(jampulang.getValue());

            // Query Insert ke tabel 'absensi'
            // Kolom: id_karyawan, tanggal, jam_masuk, jam_pulang, status
            String sql = "INSERT INTO absensi (id_karyawan, tanggal, jam_masuk, jam_pulang, status) VALUES (?, ?, ?, ?, ?)";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idKaryawan);
            pst.setString(2, tglAbsen);
            pst.setString(3, jamM);
            pst.setString(4, jamP);
            pst.setString(5, status);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Absensi Berhasil Disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Tutup form

        } catch (java.sql.SQLException e) {
            if (e.getMessage().contains("Duplicate")) {
                JOptionPane.showMessageDialog(this, "Anda sudah absen di tanggal ini!", "Gagal", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
    textID.setText("");
    jdate.setDate(null);
    jammasuk.setValue(new java.util.Date());
    jampulang.setValue(new java.util.Date());
    jcombojbtn.setSelectedIndex(0);
    jcomboRole2.setSelectedIndex(0);
    this.dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void textnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnamaActionPerformed

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDActionPerformed

    private void jcomboRole1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboRole1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboRole1ActionPerformed

    private void jcomboRole2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboRole2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboRole2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormAbsensiKaryawan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnID;
    private javax.swing.JButton btnamakywn;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner jammasuk;
    private javax.swing.JSpinner jampulang;
    private javax.swing.JComboBox<String> jcomboRole1;
    private javax.swing.JComboBox<String> jcomboRole2;
    private javax.swing.JComboBox<String> jcombojbtn;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textnama;
    // End of variables declaration//GEN-END:variables
}
