/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import javax.swing.JOptionPane;
import model.Usersmodel;
import model.UIScaler;
import Form.FormLogin2;

/**
 *
 * @author 
 */
public class FormRegister2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRegister2.class.getName());

    /**
     * Creates new form FormRegister2
     */
    public FormRegister2() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        UIScaler.scaleContainer(this.getContentPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbatal = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcomboRole = new javax.swing.JComboBox<>();
        jkonfirmasipassword = new javax.swing.JPasswordField();
        jpassword = new javax.swing.JPasswordField();
        textEmail = new javax.swing.JTextField();
        textnama = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnbatal.setText("Batal");
        btnbatal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnbatal.setPreferredSize(new java.awt.Dimension(120, 40));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnDaftar.setText("Daftar");
        btnDaftar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDaftar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Konfirmasi Password");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Jabatan");

        jcomboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "HRD", "Karyawan", " " }));
        jcomboRole.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jcomboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboRoleActionPerformed(evt);
            }
        });

        jkonfirmasipassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkonfirmasipasswordActionPerformed(evt);
            }
        });

        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });

        textnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnamaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("REGISTER");
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel21, java.awt.BorderLayout.CENTER);

        // Create form panel with GridBagLayout for centered form
        javax.swing.JPanel formPanel = new javax.swing.JPanel();
        formPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(15, 20, 15, 20);
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;

        // Nama row
        gbc.gridx = 0; gbc.gridy = 0; gbc.weightx = 0.3;
        formPanel.add(jLabel1, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formPanel.add(textnama, gbc);

        // Email row
        gbc.gridx = 0; gbc.gridy = 1; gbc.weightx = 0.3;
        formPanel.add(jLabel3, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formPanel.add(textEmail, gbc);

        // Password row
        gbc.gridx = 0; gbc.gridy = 2; gbc.weightx = 0.3;
        formPanel.add(jLabel5, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formPanel.add(jpassword, gbc);

        // Confirm Password row
        gbc.gridx = 0; gbc.gridy = 3; gbc.weightx = 0.3;
        formPanel.add(jLabel4, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formPanel.add(jkonfirmasipassword, gbc);

        // Role row
        gbc.gridx = 0; gbc.gridy = 4; gbc.weightx = 0.3;
        formPanel.add(jLabel6, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formPanel.add(jcomboRole, gbc);

        // Buttons row
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));
        buttonPanel.add(btnDaftar);
        buttonPanel.add(btnbatal);
        gbc.gridx = 0; gbc.gridy = 5; gbc.gridwidth = 2; gbc.weightx = 1.0;
        formPanel.add(buttonPanel, gbc);

        // Main layout with BorderLayout
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void textnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnamaActionPerformed

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    private void jkonfirmasipasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkonfirmasipasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkonfirmasipasswordActionPerformed

    private void jcomboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboRoleActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        String nama = textnama.getText();
        String email = textEmail.getText();
        String password = new String(jpassword.getPassword());
        String konfirmasi = new String(jkonfirmasipassword.getPassword());
        String role = jcomboRole.getSelectedItem().toString();

        // Validasi
        if (!password.equals(konfirmasi)) {
            JOptionPane.showMessageDialog(this, "Password tidak sama!");
            return;
        }


            Usersmodel model = new Usersmodel();
           boolean sukses = model.register(nama, email, password, role);


        if (sukses) {
            JOptionPane.showMessageDialog(this, "Registrasi berhasil!");

            FormLogin2 login = new FormLogin2();
            login.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Registrasi gagal!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRegister2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnbatal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcomboRole;
    private javax.swing.JPasswordField jkonfirmasipassword;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textnama;
    // End of variables declaration//GEN-END:variables
}
