/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Karyawan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.koneksi;
import model.UserSession;
import model.UIScaler;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;

/**
 *
 * @author 
 */
public class FormSlipGaji extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSlipGaji.class.getName());

    /**
     * Creates new form FormSlipGaji
     */
    public FormSlipGaji() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        UIScaler.scaleContainer(this.getContentPane());
        
        // 1. Ambil Data Login dari Session
        String idSaya = UserSession.getKaryawanId();
        String namaSaya = UserSession.getNamaKaryawan();
        String jabatanSaya = UserSession.getJabatanKaryawan();
        
        // 2. Tempel ke Text Field
        textId.setText(idSaya);
        textNama.setText(namaSaya);
        textId1.setText(jabatanSaya); // Asumsi textId1 adalah kolom Jabatan
        
        // 3. Kunci agar tidak bisa diedit
        textId.setEditable(false);
        textNama.setEditable(false);
        textId1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jcombobulan = new javax.swing.JComboBox<>();
        jcombotahun = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        textId = new javax.swing.JTextField();
        btnbatal = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnhitung = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        textId1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Bulan");

        jcombobulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));
        jcombobulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombobulanActionPerformed(evt);
            }
        });

        jcombotahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025", "2024", "2023", "2022", "2021", "2020", " " }));
        jcombotahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombotahunActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("ID Karyawan");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Nama Karyawan");

        textNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaActionPerformed(evt);
            }
        });

        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tahun");

        btnhitung.setText("Cetak Slip");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Jabatan");

        jPanel9.setBackground(new java.awt.Color(0, 51, 102));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("SLIP GAJI ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        textId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textId1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        // Create main scroll pane for responsive layout
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        javax.swing.JPanel formContentPanel = new javax.swing.JPanel();
        formContentPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(10, 20, 10, 20);
        gbc.weightx = 1.0;

        int row = 0;

        // Nama Karyawan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel17, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textNama, gbc);
        row++;

        // ID Karyawan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel18, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textId, gbc);
        row++;

        // Jabatan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel20, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textId1, gbc);
        row++;

        // Bulan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel13, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jcombobulan, gbc);
        row++;

        // Tahun
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel14, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jcombotahun, gbc);
        row++;

        // Separator
        javax.swing.JSeparator separator = new javax.swing.JSeparator();
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        formContentPanel.add(separator, gbc);
        row++;

        // Buttons
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
        buttonPanel.add(btnhitung);
        buttonPanel.add(btnbatal);

        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);
        formContentPanel.add(buttonPanel, gbc);

        scrollPane.setViewportView(formContentPanel);

        // Main layout with header and scroll pane
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcombobulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombobulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombobulanActionPerformed

    private void jcombotahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombotahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombotahunActionPerformed

    private void textNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaActionPerformed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        String idKaryawan = textId.getText();
        String nama = textNama.getText();
        String jabatan = textId1.getText();
        String bulan = jcombobulan.getSelectedItem().toString();
        String tahun = jcombotahun.getSelectedItem().toString();
        
        try {
            Connection conn = koneksi.getKoneksi();
            // Cek apakah gaji untuk bulan & tahun ini sudah ada?
            String sql = "SELECT * FROM penggajian WHERE id_karyawan = ? AND bulan = ? AND tahun = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idKaryawan);
            pst.setString(2, bulan);
            pst.setString(3, tahun);
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                // DATA DITEMUKAN! Ambil isinya
                String gajiPokok = rs.getString("gaji_pokok");
                String lembur = rs.getString("lembur");
                String potongan = rs.getString("potongan");
                String total = rs.getString("total");
                
                // Tampilkan Konfirmasi Export PDF
                int confirm = JOptionPane.showConfirmDialog(this, 
                        "Slip Gaji Ditemukan!\n" +
                        "Total Gaji Bersih: Rp " + total + "\n\n" +
                        "Simpan Slip Gaji ini sebagai PDF?", 
                        "Konfirmasi Cetak", JOptionPane.YES_NO_OPTION);
                
                if (confirm == JOptionPane.YES_OPTION) {
                    // Panggil fungsi export di bawah
                    exportToPDF(nama, idKaryawan, jabatan, bulan, tahun, gajiPokok, lembur, potongan, total);
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Mohon Maaf, Slip Gaji periode ini belum diterbitkan oleh HRD.", "Data Tidak Ditemukan", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnhitungActionPerformed

    private void textId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textId1ActionPerformed
    // Method khusus untuk membuat file PDF
    private void exportToPDF(String nama, String id, String jab, String bln, String thn, String gp, String lmbr, String pot, String tot) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan File PDF");
        // Nama file default
        fileChooser.setSelectedFile(new java.io.File("SlipGaji_" + nama + "_" + bln + ".pdf"));
        
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                String path = fileChooser.getSelectedFile().getAbsolutePath();
                if (!path.endsWith(".pdf")) path += ".pdf"; // Tambah ekstensi otomatis
                
                Document doc = new Document();
                PdfWriter.getInstance(doc, new FileOutputStream(path));
                doc.open();
                
                // --- DESAIN ISI PDF ---
                doc.add(new Paragraph("======================================"));
                doc.add(new Paragraph("          SLIP GAJI KARYAWAN          "));
                doc.add(new Paragraph("======================================"));
                doc.add(new Paragraph(" ")); // Spasi
                doc.add(new Paragraph("Nama      : " + nama));
                doc.add(new Paragraph("ID        : " + id));
                doc.add(new Paragraph("Jabatan   : " + jab));
                doc.add(new Paragraph("Periode   : " + bln + " " + thn));
                doc.add(new Paragraph("--------------------------------------"));
                doc.add(new Paragraph("Gaji Pokok: Rp " + gp));
                doc.add(new Paragraph("Lembur    : Rp " + lmbr));
                doc.add(new Paragraph("Potongan  : Rp " + pot));
                doc.add(new Paragraph("--------------------------------------"));
                doc.add(new Paragraph("TOTAL     : Rp " + tot));
                doc.add(new Paragraph("======================================"));
                
                doc.close();
                JOptionPane.showMessageDialog(this, "File PDF berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal membuat PDF: " + e.getMessage());
            }
        }
    }
    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormSlipGaji().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhitung;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox<String> jcombobulan;
    private javax.swing.JComboBox<String> jcombotahun;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textId1;
    private javax.swing.JTextField textNama;
    // End of variables declaration//GEN-END:variables
}
