/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Karyawan;
import model.Cutimodel;
import model.UIScaler;
import java.text.SimpleDateFormat; 
import javax.swing.JOptionPane; 


/**
 *
 * @author 
 */
public class FormPengajuanCuti extends javax.swing.JFrame {
    
    private Cutimodel cutiModel = new Cutimodel();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPengajuanCuti.class.getName());

    /**
     * Creates new form FormPengajuanCuti
     */
   public FormPengajuanCuti() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        UIScaler.scaleContainer(this.getContentPane());
         
        // 1. Ambil ID dan Nama dari Session 
        String myId = model.UserSession.getKaryawanId();
        String myName = model.UserSession.getNamaKaryawan();
        
        // 2. Tempel ke Text Field
        textID.setText(myId);      
        textNama.setText(myName);   
        
        // 3. Kunci Text Field (Biar karyawan tidak bisa ubah/hapus)
        textID.setEditable(false);
        textNama.setEditable(false);
        
        // 4. Set Status Default
        textstatus.setText("Pending");
        textstatus.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnajukan = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        textketerangan = new javax.swing.JTextField();
        btnbatal = new javax.swing.JButton();
        textID = new javax.swing.JTextField();
        jDatetglmulai = new com.toedter.calendar.JDateChooser();
        textstatus = new javax.swing.JTextField();
        jDatetglselesai = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Tanggal Selesai");

        jPanel9.setBackground(new java.awt.Color(0, 51, 102));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("IZIN DAN CUTI");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(162, 162, 162))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Status");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Nama Karyawan");

        textNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("ID Karyawan");

        btnajukan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnajukan.setText("Ajukan");
        btnajukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajukanActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Tanggal Mulai");

        textketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textketeranganActionPerformed(evt);
            }
        });

        btnbatal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        textstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textstatusActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Keterangan");

        // Create main scroll pane for responsive layout
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        javax.swing.JPanel formContentPanel = new javax.swing.JPanel();
        formContentPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(10, 20, 10, 20);
        gbc.weightx = 1.0;

        int row = 0;

        // Nama Karyawan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel17, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textNama, gbc);
        row++;

        // ID Karyawan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel19, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textID, gbc);
        row++;

        // Tanggal Mulai
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel18, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jDatetglmulai, gbc);
        row++;

        // Tanggal Selesai
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel20, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jDatetglselesai, gbc);
        row++;

        // Status
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel13, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textstatus, gbc);
        row++;

        // Keterangan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel14, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textketerangan, gbc);
        row++;

        // Separator
        javax.swing.JSeparator separator = new javax.swing.JSeparator();
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        formContentPanel.add(separator, gbc);
        row++;

        // Buttons
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
        buttonPanel.add(btnajukan);
        buttonPanel.add(btnbatal);

        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);
        formContentPanel.add(buttonPanel, gbc);

        scrollPane.setViewportView(formContentPanel);

        // Main layout with header and scroll pane
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaActionPerformed

    private void textketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textketeranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textketeranganActionPerformed

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDActionPerformed

    private void textstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textstatusActionPerformed

    private void btnajukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajukanActionPerformed
        // 1. Ambil Data
        String idKaryawan = textID.getText();
        String keterangan = textketerangan.getText();
        
        // 2. Validasi Input Kosong
        if (idKaryawan.isEmpty() || jDatetglmulai.getDate() == null || jDatetglselesai.getDate() == null || keterangan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi semua data (ID, Tanggal, Keterangan)!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 3. Format Tanggal (Dari Kalender ke Format Database yyyy-MM-dd)
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tglMulai = sdf.format(jDatetglmulai.getDate());
            String tglSelesai = sdf.format(jDatetglselesai.getDate());

            // 4. Panggil Model
            // (Pastikan Cutimodel.java Anda sudah memiliki method ajukanCuti dengan 4 parameter ini)
            boolean sukses = cutiModel.ajukanCuti(idKaryawan, tglMulai, tglSelesai, keterangan);

            // 5. Feedback
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Pengajuan Cuti Berhasil Dikirim!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); // Tutup form setelah berhasil
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengajukan cuti. Periksa ID Karyawan.", "Gagal", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnajukanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPengajuanCuti().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajukan;
    private javax.swing.JButton btnbatal;
    private com.toedter.calendar.JDateChooser jDatetglmulai;
    private com.toedter.calendar.JDateChooser jDatetglselesai;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textketerangan;
    private javax.swing.JTextField textstatus;
    // End of variables declaration//GEN-END:variables
}
