/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Karyawan;
import javax.swing.JOptionPane;
import model.UIScaler;

/**
 *
 * @author 
 */
public class KaryawanDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KaryawanDashboard.class.getName());

    /**
     * Creates new form KaryawanDashboard
     */
    public KaryawanDashboard() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        UIScaler.scaleContainer(this.getContentPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Btnabsen = new javax.swing.JButton();
        btnIzindancuti = new javax.swing.JButton();
        btnslipgaji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KARYAWAN DASHBOARD");

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.insets = new java.awt.Insets(30, 20, 60, 20);
        gbc.weightx = 1.0;
        jPanel1.add(jLabel9, gbc);

        Btnabsen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Btnabsen.setText("Absensi Harian");
        Btnabsen.setPreferredSize(new java.awt.Dimension(200, 60));
        Btnabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnabsenActionPerformed(evt);
            }
        });
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);
        gbc.weightx = 0.33;
        gbc.weighty = 1.0;
        jPanel1.add(Btnabsen, gbc);

        btnIzindancuti.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnIzindancuti.setText("Pengajuan Cuti");
        btnIzindancuti.setPreferredSize(new java.awt.Dimension(200, 60));
        btnIzindancuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzindancutiActionPerformed(evt);
            }
        });
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);
        gbc.weightx = 0.33;
        jPanel1.add(btnIzindancuti, gbc);

        btnslipgaji.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnslipgaji.setText("Slip Gaji");
        btnslipgaji.setPreferredSize(new java.awt.Dimension(200, 60));
        btnslipgaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnslipgajiActionPerformed(evt);
            }
        });
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.insets = new java.awt.Insets(20, 20, 20, 20);
        gbc.weightx = 0.33;
        jPanel1.add(btnslipgaji, gbc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnabsenActionPerformed
        try {
            // Membuka form yang ada di package HRD
            new shared.FormAbsensiKaryawan().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membuka Hitung Gaji: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnabsenActionPerformed

    private void btnIzindancutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzindancutiActionPerformed
        try {
            // Membuka form di package yang sama (Karyawan)
            new FormPengajuanCuti().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Form Pengajuan Cuti belum dibuat!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzindancutiActionPerformed

    private void btnslipgajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnslipgajiActionPerformed
        try {
            // Membuka form di package yang sama (Karyawan)
            new FormSlipGaji().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Form Slip Gaji belum dibuat!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnslipgajiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KaryawanDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnabsen;
    private javax.swing.JButton btnIzindancuti;
    private javax.swing.JButton btnslipgaji;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
