/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;
import javax.swing.JOptionPane;
import Karyawan.FormPengajuanCuti;
import Karyawan.FormSlipGaji;  


/**
 *
 * @author 
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDasbord
     */
    public AdminDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Btnhitunggaji = new javax.swing.JButton();
        btnIzindancuti = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        btnlabsensi = new javax.swing.JButton();
        btnlabsensi1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADMIN");

        Btnhitunggaji.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Btnhitunggaji.setText("Absensi Harian");
        Btnhitunggaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnhitunggajiActionPerformed(evt);
            }
        });

        btnIzindancuti.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnIzindancuti.setText("Pengajuan Cuti");
        btnIzindancuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzindancutiActionPerformed(evt);
            }
        });

        btnlaporan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnlaporan.setText(" Laporan Penggajian");
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });

        btnlabsensi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnlabsensi.setText("Laporan Absensi");
        btnlabsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlabsensiActionPerformed(evt);
            }
        });

        btnlabsensi1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnlabsensi1.setText("Slip Gaji");
        btnlabsensi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlabsensi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnlabsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnhitunggaji, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIzindancuti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlabsensi1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnhitunggaji)
                    .addComponent(btnIzindancuti))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlabsensi)
                    .addComponent(btnlaporan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnlabsensi1)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnhitunggajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnhitunggajiActionPerformed
        try {
            // Membuka Form Absensi (Gunakan shared.FormAbsensiKaryawan jika itu yang dipakai)
            // Atau jika Admin punya form absensi sendiri, sesuaikan namanya.
            // Di sini saya arahkan ke FormAbsensiKaryawan agar Admin bisa absen juga.
            new shared.FormAbsensiKaryawan().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membuka Absensi: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnhitunggajiActionPerformed

    private void btnIzindancutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzindancutiActionPerformed
      try {
            // Membuka Form Persetujuan Cuti (FormIzinCuti yang ada di HRD)
            // Admin biasanya punya hak akses yang sama dengan HRD untuk approval
            new Karyawan.FormPengajuanCuti().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membuka Form Cuti: " + e.getMessage());
        }
    }//GEN-LAST:event_btnIzindancutiActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
      try {
            // Membuka Form Laporan Penggajian
            // Pastikan file 'laporanpenggajian.java' ada di package Admin
            new laporanpenggajian().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Form Laporan Penggajian belum dibuat!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void btnlabsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlabsensiActionPerformed
      try {
            // Membuka Form Laporan Absensi (laporanabsensi.java di package Admin)
            new laporanabsensi().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Form Laporan Absensi belum dibuat!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnlabsensiActionPerformed

    private void btnlabsensi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlabsensi1ActionPerformed
        try {
            // Membuka Form Slip Gaji (menggunakan form yang sama dengan Karyawan)
            new Karyawan.FormSlipGaji().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membuka Slip Gaji: " + e.getMessage());
        }
    }//GEN-LAST:event_btnlabsensi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnhitunggaji;
    private javax.swing.JButton btnIzindancuti;
    private javax.swing.JButton btnlabsensi;
    private javax.swing.JButton btnlabsensi1;
    private javax.swing.JButton btnlaporan;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
