/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HRD;
import model.Gajimodel;
import model.Karyawanmodel;
import model.UIScaler;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class FormHitungGaji extends javax.swing.JFrame {
    
    private Gajimodel gajiModel = new Gajimodel();
    private Karyawanmodel karyModel = new Karyawanmodel();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormHitungGaji.class.getName());

    /**
     * Creates new form FormHitungGaji
     */
   public FormHitungGaji() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        jTextField1.setEditable(false);
        UIScaler.scaleContainer(this.getContentPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // Method untuk menghitung gaji bersih
    private int hitungGajiBersih() {
        try {
            // Ambil nilai, jika kosong dianggap 0
            int gajiPokok = textupahlembur.getText().isEmpty() ? 0 : Integer.parseInt(textupahlembur.getText());
            int jamLembur = textpotongan.getText().isEmpty() ? 0 : Integer.parseInt(textpotongan.getText());
            int upahLemburPerJam = textpotongan2.getText().isEmpty() ? 0 : Integer.parseInt(textpotongan2.getText());
            int potongan = textpotongan1.getText().isEmpty() ? 0 : Integer.parseInt(textpotongan1.getText());

            // Rumus Gaji
            int totalLembur = jamLembur * upahLemburPerJam;
            int totalGaji = gajiPokok + totalLembur - potongan;

            // Tampilkan hasil (Format Rupiah sederhana)
            jTextField1.setText("Rp " + totalGaji);
            
            return totalGaji; // Kembalikan nilai untuk disimpan nanti

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan hanya angka!", "Error Input", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        textId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textupahlembur = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textpotongan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnbatal = new javax.swing.JButton();
        btnhitung = new javax.swing.JButton();
        combojbtn = new javax.swing.JComboBox<>();
        btnsimpan = new javax.swing.JButton();
        textpotongan1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        textpotongan2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jcombobulan = new javax.swing.JComboBox<>();
        jcombotahun = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("ID Karyawan");

        textNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaActionPerformed(evt);
            }
        });

        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tahun");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Jabatan");

        jPanel9.setBackground(new java.awt.Color(0, 51, 102));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("HITUNG GAJI ");
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Bulan");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Nama Karyawan");

        textupahlembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textupahlemburActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Gaji Pokok");

        textpotongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpotonganActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Jam Lembur");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("TOTAL GAJI BERSIH :");

        jTextField1.setToolTipText("Rp");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        combojbtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "HRD", "Karyawan" }));

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        textpotongan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpotongan1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Upah Lembur / Jam");

        textpotongan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpotongan2ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Potongan");

        jcombobulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));
        jcombobulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombobulanActionPerformed(evt);
            }
        });

        jcombotahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025", "2024", "2023", "2022", "2021", "2020", " " }));
        jcombotahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombotahunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        
        // Create main scroll pane for responsive layout
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        javax.swing.JPanel formContentPanel = new javax.swing.JPanel();
        formContentPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(10, 20, 10, 20);
        gbc.weightx = 1.0;
        
        int row = 0;
        
        // Nama Karyawan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel17, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textNama, gbc);
        row++;
        
        // ID Karyawan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel18, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textId, gbc);
        row++;
        
        // Jabatan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel20, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(combojbtn, gbc);
        row++;
        
        // Bulan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel13, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jcombobulan, gbc);
        row++;
        
        // Tahun
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel14, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(jcombotahun, gbc);
        row++;
        
        // Gaji Pokok
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel15, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textupahlembur, gbc);
        row++;
        
        // Jam Lembur
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel16, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textpotongan, gbc);
        row++;
        
        // Upah Lembur per Jam
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel22, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textpotongan2, gbc);
        row++;
        
        // Potongan
        gbc.gridx = 0; gbc.gridy = row; gbc.weightx = 0.3;
        formContentPanel.add(jLabel23, gbc);
        gbc.gridx = 1; gbc.weightx = 0.7;
        formContentPanel.add(textpotongan1, gbc);
        row++;
        
        // Add separator
        javax.swing.JSeparator separator = new javax.swing.JSeparator();
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2;
        formContentPanel.add(separator, gbc);
        row++;
        
        // Total Gaji Panel
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2;
        formContentPanel.add(jPanel1, gbc);
        row++;
        
        // Buttons Panel
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));
        buttonPanel.add(btnhitung);
        buttonPanel.add(btnsimpan);
        buttonPanel.add(btnbatal);
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; gbc.weighty = 1.0;
        gbc.anchor = java.awt.GridBagConstraints.SOUTH;
        formContentPanel.add(buttonPanel, gbc);
        
        scrollPane.setViewportView(formContentPanel);
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaActionPerformed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdActionPerformed

    private void textupahlemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textupahlemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textupahlemburActionPerformed

    private void textpotonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpotonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpotonganActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        hitungGajiBersih();
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // 1. Ambil Data Teks
        String idKaryawan = textId.getText();
        String bulan = jcombobulan.getSelectedItem().toString();
        String tahun = jcombotahun.getSelectedItem().toString();
        
        // 2. Cek apakah ID kosong
        if (idKaryawan.isEmpty() || textupahlembur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi ID Karyawan dan Gaji Pokok!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Hitung ulang (untuk memastikan data update)
        hitungGajiBersih();
        
        try {
            // 4. Ambil Data Angka
            int gajiPokok = Integer.parseInt(textupahlembur.getText());
            int jamLembur = textpotongan.getText().isEmpty() ? 0 : Integer.parseInt(textpotongan.getText());
            int upahLemburPerJam = textpotongan2.getText().isEmpty() ? 0 : Integer.parseInt(textpotongan2.getText());
            int potongan = textpotongan1.getText().isEmpty() ? 0 : Integer.parseInt(textpotongan1.getText());

            // 5. Kirim ke Database lewat Model
            boolean sukses = gajiModel.hitungDanSimpan(idKaryawan, gajiPokok, jamLembur, upahLemburPerJam, potongan, bulan, tahun);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Gaji Berhasil Disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); // Tutup form
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan. ID Karyawan mungkin salah atau Gaji bulan ini sudah ada.", "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        } catch(Exception e) {
             System.out.println("Error simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void textpotongan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpotongan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpotongan1ActionPerformed

    private void textpotongan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpotongan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpotongan2ActionPerformed

    private void jcombobulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombobulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombobulanActionPerformed

    private void jcombotahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombotahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombotahunActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormHitungGaji().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> combojbtn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcombobulan;
    private javax.swing.JComboBox<String> jcombotahun;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textpotongan;
    private javax.swing.JTextField textpotongan1;
    private javax.swing.JTextField textpotongan2;
    private javax.swing.JTextField textupahlembur;
    // End of variables declaration//GEN-END:variables
}
